server:
  port: 8082
  servlet:
    contextPath: /api

spring:
  application:
    name: customer

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/customer_db
    username: user
    password: password

  security:
    user:
      name: zen
      password: password
      roles: ADMIN

  loan:
    host: http://localhost:8081/api/loan
    endpoint:
      getInfo: info

restTemplate:
  connectionTimeOut: 5000
  readTimeOut: 10000